-- ============================================================
-- DPDP ACT 2023 + DPDP RULES 2025 SEED DATA
-- Baseline Data Inventory, Processing Purposes, Multilingual Notices,
-- Retention Policies, Processors, and Grievance Setup
-- ============================================================

-- 1. SEED PROCESSING PURPOSES
INSERT INTO processing_purposes (id, code, name, name_hi, name_gu, description, description_hi, description_gu, legal_basis, is_mandatory, is_active) VALUES
(1, 'application_processing', 'Driving Licence Application Processing', 'ड्राइविंग लाइसेंस आवेदन प्रसंस्करण', 'ડ્રાઇવિંગ લાયસન્સ અરજી પ્રક્રિયા', 'Processing applicant information and documentation for RTO submission.', 'आरटीओ सबमिशन के लिए आवेदक की जानकारी और दस्तावेजों का प्रसंस्करण।', 'RTO સબમિશન માટે અરજદારની માહિતી અને દસ્તાવેજોની પ્રક્રિયા.', 'consent', 1, 1),
(2, 'identity_verification', 'Identity & Age Verification', 'पहचान एवं आयु सत्यापन', 'ઓળખ અને ઉંમર ચકાસણી', 'Verifying age and identity credentials to comply with Motor Vehicles Act.', 'मोटर वाहन अधिनियम के अनुपालन के लिए आयु और पहचान प्रमाण का सत्यापन।', 'મોટર વાહન અધિનિયમના પાલન માટે ઉંમર અને ઓળખ પુરાવાની ચકાસણી.', 'legal_requirement', 1, 1),
(3, 'user_account', 'Citizen Account Management', 'नागरिक खाता प्रबंधन', 'નાગરિક ખાતું સંચાલન', 'Maintaining authenticated user session, draft state, and security credentials.', 'प्रमाणीकृत उपयोगकर्ता सत्र, ड्राफ्ट स्थिति और सुरक्षा क्रेडेंशियल्स का रखरखाव।', 'પ્રમાણિત યુઝર સેશન, ડ્રાફ્ટ સ્થિતિ અને સુરક્ષા ઓળખપત્રોની જાળવણી.', 'legitimate_use', 1, 1),
(4, 'service_communication', 'Service Communication & Tracking Alerts', 'सेवा संचार एवं ट्रैकिंग अलर्ट', 'સેવા સંચાર અને ટ્રેકિંગ ચેતવણીઓ', 'Sending transactional SMS/email updates regarding application progress and test dates.', 'आवेदन की प्रगति और परीक्षण तिथियों के संबंध में लेनदेन संबंधी एसएमएस/ईमेल अपडेट भेजना।', 'અરજીની પ્રગતિ અને ટેસ્ટ તારીખો સંબંધિત ટ્રાન્ઝેક્શનલ એસએમએસ/ઇમેઇલ અપડેટ્સ મોકલવા.', 'consent', 1, 1),
(5, 'payment_processing', 'Fee Settlement & Payment Processing', 'शुल्क निपटान एवं भुगतान प्रसंस्करण', 'ફી પતાવટ અને ચુકવણી પ્રક્રિયા', 'Processing government and platform facilitation fees through authorized payment gateways.', 'अधिकृत भुगतान गेटवे के माध्यम से सरकारी और प्लेटफ़ॉर्म सुविधा शुल्क का प्रसंस्करण।', 'અધિકૃત પેમેન્ટ ગેટવે દ્વારા સરકારી અને પ્લેટફોર્મ સુવિધા ફીની પ્રક્રિયા.', 'contract', 1, 1),
(6, 'document_verification', 'Document Scrutiny & RTO Prep', 'दस्तावेज़ जांच एवं आरटीओ तैयारी', 'દસ્તાવેજ ચકાસણી અને RTO તૈયારી', 'Checking clarity, validity, and completeness of uploaded identity and address proofs.', 'अपलोड किए गए पहचान और पते के प्रमाणों की स्पष्टता, वैधता और पूर्णता की जांच करना।', 'અપલોડ કરેલા ઓળખ અને સરનામાના પુરાવાની સ્પષ્ટતા, માન્યતા અને પૂર્ણતાની ચકાસણી.', 'consent', 1, 1),
(7, 'security', 'Platform Security & Abuse Prevention', 'प्लेटफ़ॉर्म सुरक्षा एवं दुरुपयोग रोकथाम', 'પ્લેટફોર્મ સુરક્ષા અને દુરુપયોગ નિવારણ', 'Preventing unauthorized account access, DDoS attacks, and fraudulent bot submissions.', 'अनधिकृत खाता पहुंच, डीडीओएस हमलों और धोखाधड़ी वाले बॉट सबमिशन को रोकना।', 'અનધિકૃત એકાઉન્ટ એક્સેસ, DDoS હુમલા અને છેતરપિંડીયુક્ત બોટ સબમિશન અટકાવવા.', 'legal_requirement', 1, 1),
(8, 'legal_compliance', 'Statutory Record Keeping & DPDP Compliance', 'वैधानिक रिकॉर्ड कीपिंग एवं डीपीडीपी अनुपालन', 'વૈધાનિક રેકોર્ડ રાખવા અને DPDP પાલન', 'Maintaining audit trails and compliance records under DPDP Act 2023.', 'डीपीडीपी अधिनियम 2023 के तहत ऑडिट ट्रेल्स और अनुपालन रिकॉर्ड बनाए रखना।', 'DPDP એક્ટ 2023 હેઠળ ઓડિટ ટ્રેલ્સ અને પાલન રેકોર્ડ્સ જાળવવા.', 'legal_requirement', 1, 1),
(9, 'grievance_management', 'Grievance Redressal & Support', 'शिकायत निवारण एवं सहायता', 'ફરિયાદ નિવારણ અને સહાય', 'Resolving citizen grievances and exercising Data Principal statutory rights.', 'नागरिक शिकायतों का समाधान और डेटा प्रिंसिपल वैधानिक अधिकारों का प्रयोग करना।', 'નાગરિક ફરિયાદોનું નિરાકરણ અને ડેટા પ્રિન્સિપાલ વૈધાનિક અધિકારોનો ઉપયોગ કરવો.', 'legal_requirement', 1, 1),
(10, 'fraud_prevention', 'Fraud Prevention & Duplicate Detection', 'धोखाधड़ी रोकथाम एवं डुप्लिकेट पहचान', 'છેતરપિંડી નિવારણ અને ડુપ્લિકેટ શોધ', 'Detecting forged documents and repeated unauthorized application submissions.', 'जाली दस्तावेजों और बार-बार अनधिकृत आवेदन प्रस्तुतियों का पता लगाना।', 'બનાવટી દસ્તાવેજો અને વારંવાર અનધિકૃત અરજી સબમિશન શોધવા.', 'legitimate_use', 1, 1),
(11, 'analytics', 'Citizen Experience Analytics (Optional)', 'नागरिक अनुभव विश्लेषण (वैकल्पिक)', 'નાગરિક અનુભવ વિશ્લેષણ (વૈકલ્પિક)', 'Aggregated and privacy-preserving insights to improve portal usability and flow.', 'पोर्टल की उपयोगिता और प्रवाह को बेहतर बनाने के लिए समग्र और गोपनीयता-संरक्षण अंतर्दृष्टि।', 'પોર્ટલ ઉપયોગિતા અને પ્રવાહ સુધારવા માટે એકત્રિત અને ગોપનીયતા-સંરક્ષિત આંતરદૃષ્ટિ.', 'consent', 0, 1),
(12, 'marketing', 'Informational Updates & Tips (Optional)', 'सूचनात्मक अपडेट और युक्तियाँ (वैकल्पिक)', 'માહિતીપ્રદ અપડેટ્સ અને ટિપ્સ (વૈકલ્પિક)', 'Occasional alerts regarding new transport schemes and road safety advisories.', 'नई परिवहन योजनाओं और सड़क सुरक्षा सलाह के संबंध में सामयिक अलर्ट।', 'નવી પરિવહન યોજનાઓ અને માર્ગ સલામતી સલાહકારો અંગે સામયિક ચેતવણીઓ.', 'consent', 0, 1) ON CONFLICT DO NOTHING;
-- 2. SEED DATA INVENTORY
INSERT INTO data_inventory (field_id, field_name, data_category, description, purpose, legal_basis, required, sensitivity_level, storage_location, user_visible, exportable, erasable, correctable) VALUES
('first_name', 'First Name', 'identity', 'Legal given name of the applicant', 'application_processing', 'consent', 1, 'standard', 'database', 1, 1, 1, 1),
('middle_name', 'Middle Name', 'identity', 'Middle name or patronymic name', 'application_processing', 'consent', 0, 'standard', 'database', 1, 1, 1, 1),
('last_name', 'Last Name / Surname', 'identity', 'Family or surname of the applicant', 'application_processing', 'consent', 1, 'standard', 'database', 1, 1, 1, 1),
('date_of_birth', 'Date of Birth', 'identity', 'Date of birth for age qualification check', 'identity_verification', 'legal_requirement', 1, 'sensitive', 'database', 1, 1, 0, 1),
('gender', 'Gender', 'identity', 'Gender identity as recorded in government records', 'application_processing', 'consent', 1, 'standard', 'database', 1, 1, 1, 1),
('mobile', 'Mobile Number', 'contact', 'Primary mobile number verified via OTP for 2FA and alerts', 'service_communication', 'consent', 1, 'sensitive', 'database', 1, 1, 0, 1),
('email', 'Email Address', 'contact', 'Electronic mail address for digital receipts and updates', 'service_communication', 'consent', 0, 'standard', 'database', 1, 1, 1, 1),
('blood_group', 'Blood Group', 'biometric', 'Blood group required by MoRTH for DL printing and emergency response', 'application_processing', 'legal_requirement', 0, 'sensitive', 'database', 1, 1, 1, 1),
('identity_type', 'Identity Proof Type', 'identity', 'Selected government identity document (Aadhaar, Passport, etc.)', 'identity_verification', 'legal_requirement', 1, 'standard', 'database', 1, 1, 1, 1),
('identity_number', 'Identity Document Number', 'identity', 'Masked or hashed identity document number', 'identity_verification', 'legal_requirement', 1, 'critical', 'encrypted_vault', 1, 0, 0, 1),
('current_address', 'Current Residential Address', 'address', 'House, street, locality, city, district, state, pincode', 'application_processing', 'consent', 1, 'sensitive', 'database', 1, 1, 1, 1),
('permanent_address', 'Permanent Address', 'address', 'Permanent domicile address as per domicile certificate', 'application_processing', 'consent', 1, 'sensitive', 'database', 1, 1, 1, 1),
('existing_licence_number', 'Existing Licence Number', 'licence_data', 'Previous driving licence number for renewal or endorsement', 'application_processing', 'consent', 0, 'standard', 'database', 1, 1, 1, 1),
('uploaded_documents', 'Uploaded Verification Documents', 'documents', 'Scanned files (photo, age proof, address proof, medical fitness)', 'document_verification', 'consent', 1, 'critical', 'private_storage', 1, 1, 1, 1),
('payment_reference', 'Payment Transaction ID', 'financial', 'Gateway transaction ID and payment status timestamp', 'payment_processing', 'contract', 1, 'sensitive', 'database', 1, 1, 0, 0),
('government_reference', 'Government Application ID', 'government_reference', 'Application number assigned by Parivahan / State RTO portal', 'application_processing', 'legal_requirement', 0, 'standard', 'database', 1, 1, 0, 0),
('operator_notes', 'Operator Scrutiny Notes', 'operator_notes', 'Internal verification notes and status rationale', 'legal_compliance', 'legal_requirement', 0, 'standard', 'database', 1, 0, 0, 0),
('guardian_info', 'Parent / Guardian Details', 'identity', 'Minor applicant guardian name, contact, and consent evidence', 'identity_verification', 'legal_requirement', 0, 'critical', 'database', 1, 1, 1, 1) ON CONFLICT DO NOTHING;
-- 3. SEED RETENTION POLICIES
INSERT INTO retention_policies (id, policy_name, data_category, purpose, retention_period, retention_unit, deletion_action, legal_basis, legal_hold_supported, is_active) VALUES
(1, 'Applicant Account Profile', 'contact', 'user_account', 365, 'days', 'anonymize', 'consent', 1, 1),
(2, 'Draft Application Data', 'application_data', 'application_processing', 90, 'days', 'purge', 'legitimate_use', 1, 1),
(3, 'Submitted Application Records', 'application_data', 'legal_compliance', 5, 'years', 'archive', 'legal_requirement', 1, 1),
(4, 'Uploaded Identity Documents', 'documents', 'document_verification', 180, 'days', 'purge', 'legal_requirement', 1, 1),
(5, 'Financial & Payment Logs', 'financial', 'payment_processing', 7, 'years', 'archive', 'legal_requirement', 1, 1),
(6, 'Consent & Withdrawal History', 'legal', 'legal_compliance', 10, 'years', 'archive', 'legal_requirement', 1, 1),
(7, 'Security & Access Logs', 'technical', 'security', 365, 'days', 'purge', 'legal_requirement', 1, 1),
(8, 'Privacy Requests & Grievances', 'legal', 'grievance_management', 3, 'years', 'archive', 'legal_requirement', 1, 1) ON CONFLICT DO NOTHING;
-- 4. SEED PRIVACY NOTICE & VERSIONS
INSERT INTO privacy_notices (id, slug, title, title_hi, title_gu, is_active) VALUES
(1, 'dlf-master-notice', 'Driving License Form Master Privacy Notice', 'ड्राइविंग लाइसेंस फॉर्म मास्टर गोपनीयता सूचना', 'ડ્રાઇવિંગ લાયસન્સ ફોર્મ માસ્ટર ગોપનીયતા સૂચના', 1) ON CONFLICT DO NOTHING;
INSERT INTO privacy_notice_versions (id, notice_id, version, language, title, content, summary, purposes_json, data_categories_json, status) VALUES
(1, 1, '1.0', 'en', 'Master Privacy Notice (English)',
'# Digital Personal Data Protection Notice\n\n**Effective Date:** September 2026\n**Statutory Baseline:** Digital Personal Data Protection Act, 2023 (DPDP Act) and DPDP Rules, 2025.\n\n### 1. Who We Are\nDriving License Form ("Platform", "we", "us") is an independent citizen facilitation platform assisting applicants with driving and learner licence application preparation for Gujarat, Rajasthan, and Uttar Pradesh.\n\n### 2. What Personal Data We Collect\nWe collect only personal data necessary for your licence application:\n- **Identity & Demographics:** Name, date of birth, gender, father/guardian name, blood group.\n- **Contact Information:** Mobile number (verified via OTP), email address.\n- **Address Information:** Current and permanent address with postal PIN code.\n- **Supporting Documents:** Age proof, address proof, passport photograph, signature.\n- **Technical & Security Data:** IP address, session timestamps, audit logs.\n\n### 3. Why We Collect It & Lawful Basis\n- **Service Processing (Consent):** Form filling and document packaging for RTO dispatch.\n- **Identity Verification (Legal Requirement):** Ensuring statutory age and eligibility under the Motor Vehicles Act.\n- **Transactional Alerts (Consent):** SMS and tracking updates on application status.\n- **Security & Fraud Prevention (Legitimate Use & Legal Obligation):** Ensuring account integrity.\n\n### 4. Data Sharing & Third-Party Processors\nYour data is shared strictly with authorized partners: State RTO Authorities, RBI-regulated Payment Gateways, and TRAI-compliant SMS gateways within India. We NEVER sell or monetize citizen data.\n\n### 5. Your Statutory Rights as a Data Principal\nYou have the right under DPDP Act 2023 to:\n- **Access:** Review your stored personal data anytime at `/account/privacy`.\n- **Correction & Completion:** Correct outdated or erroneous details.\n- **Erasure:** Request deletion of personal data where statutory retention has ended.\n- **Consent Withdrawal:** Withdraw consent for optional processing.\n- **Nomination:** Designate another individual to act on your behalf.\n- **Grievance Redressal:** Raise complaints directly to our Grievance Officer.\n\n### 6. Grievance Officer & Data Protection Officer Contact\n**Officer:** Shri Animesh Sharma, Data Protection Officer\n**Email:** dpo@drivinglicenceform.in | privacy@drivinglicenceform.in\n**Address:** Privacy & Compliance Cell, Driving License Form, Gandhinagar, Gujarat 382010.\n**Response SLA:** Acknowledged within 24 hours, resolved within statutory timelines.',
'Comprehensive DPDP-compliant notice explaining data collection, processing purposes, sharing, citizen rights, and grievance officer details.',
'["application_processing","identity_verification","service_communication","payment_processing","document_verification","security","legal_compliance"]',
'["identity","contact","address","biometric","documents","financial"]',
'published'),

(2, 1, '1.0', 'hi', 'मास्टर गोपनीयता सूचना (हिन्दी)',
'# डिजिटल व्यक्तिगत डेटा संरक्षण सूचना\n\n**प्रभावी तिथि:** सितम्बर 2026\n**वैधानिक आधार:** डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम, 2023 (डीपीडीपी अधिनियम) एवं डीपीडीपी नियम, 2025।\n\n### 1. हम कौन हैं\nड्राइविंग लाइसेंस फॉर्म ("प्लेटफ़ॉर्म", "हम") एक स्वतंत्र नागरिक सुविधा प्लेटफ़ॉर्म है जो गुजरात, राजस्थान और उत्तर प्रदेश के नागरिकों को ड्राइविंग एवं लर्नर लाइसेंस आवेदन तैयार करने में सहायता करता है।\n\n### 2. हम कौन सा व्यक्तिगत डेटा एकत्र करते हैं\n- **पहचान एवं जनसांख्यिकी:** पूरा नाम, जन्म तिथि, लिंग, पिता/अभिभावक का नाम, रक्त समूह।\n- **संपर्क विवरण:** ओटीपी से सत्यापित मोबाइल नंबर, ईमेल पता।\n- **निवास का पता:** वर्तमान और स्थायी पता एवं पिन कोड।\n- **सहायक दस्तावेज़:** आयु प्रमाण, पता प्रमाण, फोटो, हस्ताक्षर।\n- **सुरक्षा एवं तकनीकी डेटा:** आईपी पता, सत्र समय, सुरक्षा लॉग।\n\n### 3. डेटा एकत्र करने का उद्देश्य एवं कानूनी आधार\n- **आवेदन प्रसंस्करण (सहमति):** आरटीओ सबमिशन के लिए फॉर्म तैयार करना।\n- **पहचान सत्यापन (कानूनी आवश्यकता):** मोटर वाहन अधिनियम के तहत पात्रता की पुष्टि।\n- **लेनदेन संबंधी अलर्ट (सहमति):** एसएमएस और ट्रैकिंग अपडेट।\n- **प्लेटफ़ॉर्म सुरक्षा (वैध उपयोग):** धोखाधड़ी और अनधिकृत पहुंच की रोकथाम।\n\n### 4. डेटा साझाकरण\nआपका डेटा केवल आरटीओ प्राधिकारियों, आरबीआई विनियमित पेमेंट गेटवे और अधिकृत एसएमएस प्रदाताओं के साथ भारत के भीतर साझा किया जाता है। हम नागरिकों का डेटा कभी नहीं बेचते हैं।\n\n### 5. आपके वैधानिक अधिकार (डेटा प्रिंसिपल अधिकार)\n- **डेटा तक पहुंच:** `/account/privacy` पर कभी भी अपना डेटा देखें।\n- **सुधार एवं अद्यतन:** गलत डेटा को सही करने का अनुरोध करें।\n- **डेटा मिटाना (इरेज़र):** वैधानिक अवधि समाप्त होने पर डेटा हटाने का अनुरोध करें।\n- **सहमति वापस लेना:** वैकल्पिक सेवाओं के लिए सहमति कभी भी वापस लें।\n- **नामांकन:** अपनी ओर से कार्य करने हेतु किसी व्यक्ति को नामित करें।\n- **शिकायत निवारण:** सीधे हमारे शिकायत अधिकारी के पास शिकायत दर्ज करें।\n\n### 6. शिकायत अधिकारी एवं डीपीओ संपर्क\n**अधिकारी:** श्री अनिमेश शर्मा, डेटा संरक्षण अधिकारी\n**ईमेल:** dpo@drivinglicenceform.in\n**पता:** गोपनीयता कक्ष, ड्राइविंग लाइसेंस फॉर्म, गांधीनगर, गुजरात 382010।',
'डीपीडीपी अधिनियम 2023 के तहत व्यापक सूचना जो डेटा संग्रह, उद्देश्य, नागरिक अधिकार और शिकायत संपर्क का विवरण देती है।',
'["application_processing","identity_verification","service_communication","payment_processing","document_verification","security","legal_compliance"]',
'["identity","contact","address","biometric","documents","financial"]',
'published'),

(3, 1, '1.0', 'gu', 'માસ્ટર ગોપનીયતા સૂચના (ગુજરાતી)',
'# ડિજિટલ પર્સનલ ડેટા પ્રોટેક્શન નોટિસ\n\n**અમલી તારીખ:** સપ્ટેમ્બર 2026\n**કાનૂની આધાર:** ડિજિટલ પર્સનલ ડેટા પ્રોટેક્શન એક્ટ, 2023 (DPDP એક્ટ) અને DPDP નિયમો, 2025.\n\n### 1. અમે કોણ છીએ\nડ્રાઇવિંગ લાયસન્સ ફોર્મ ("પ્લેટફોર્મ", "અમે") એ એક સ્વતંત્ર નાગરિક સુવિધા પ્લેટફોર્મ છે જે ગુજરાત, રાજસ્થાન અને ઉત્તર પ્રદેશના નાગરિકોને ડ્રાઇવિંગ અને લર્નર લાયસન્સ અરજીઓ તૈયાર કરવામાં મદદ કરે છે.\n\n### 2. અમે કયો વ્યક્તિગત ડેટા એકત્રિત કરીએ છીએ\n- **ઓળખ અને વસ્તીવિષયક:** પૂરું નામ, જન્મ તારીખ, જાતિ, પિતા/વાલીનું નામ, રક્ત જૂથ.\n- **સંપર્ક માહિતી:** મોબાઇલ નંબર (OTP દ્વારા ચકાસાયેલ), ઇમેઇલ સરનામું.\n- **સરનામું:** વર્તમાન અને કાયમી સરનામું તેમજ પિનકોડ.\n- **પુરાવા દસ્તાવેજો:** ઉંમરનો પુરાવો, સરનામાનો પુરાવો, ફોટોગ્રાફ, સહી.\n- **સુરક્ષા ડેટા:** IP સરનામું, સત્ર સમય, સુરક્ષા લૉગ્સ.\n\n### 3. ડેટા એકત્રિત કરવાનો હેતુ અને કાનૂની આધાર\n- **અરજી પ્રક્રિયા (સંમતિ):** RTO સબમિશન માટે ફોર્મ તૈયાર કરવું.\n- **ઓળખ ચકાસણી (કાનૂની જરૂરિયાત):** મોટર વાહન અધિનિયમ હેઠળ યોગ્યતાની ચકાસણી.\n- **સંચાર ચેતવણીઓ (સંમતિ):** અરજીની સ્થિતિ અંગે SMS અને ટ્રેકિંગ અપડેટ્સ.\n- **પ્લેટફોર્મ સુરક્ષા (કાયદેસર ઉપયોગ):** છેતરપિંડી અટકાવવી.\n\n### 4. ડેટા શેરિંગ\nતમારો ડેટા ફક્ત અધિકૃત RTO સત્તાવાળાઓ, RBI-નિયંત્રિત પેમેન્ટ ગેટવે અને અધિકૃત SMS પ્રદાતાઓ સાથે ભારતમાં જ શેર થાય છે. અમે ક્યારેય નાગરિક ડેટા વેચતા નથી.\n\n### 5. ડેટા પ્રિન્સિપાલ તરીકે તમારા કાનૂની અધિકારો\n- **ડેટા એક્સેસ:** `/account/privacy` પર કોઈપણ સમયે તમારો સંગ્રહિત ડેટા જુઓ.\n- **સુધારો:** ખોટી વિગતો સુધારવાની વિનંતી કરો.\n- **ડેટા ડિલીટ:** કાનૂની જાળવણી પૂર્ણ થયા પછી ડેટા કાઢી નાખવાની વિનંતી કરો.\n- **સંમતિ પાછી ખેંચવી:** વૈકલ્પિક પ્રક્રિયા માટે સંમતિ સરળતાથી પાછી ખેંચો.\n- **નોમિનેશન:** તમારી વતી કામ કરવા માટે નોમિની નિયુક્ત કરો.\n- **ફરિયાદ નિવારણ:** ફરિયાદ અધિકારી પાસે સીધી ફરિયાદ નોંધાવો.\n\n### 6. ફરિયાદ અધિકારી અને DPO સંપર્ક\n**અધિકારી:** શ્રી અનિમેષ શર્મા, ડેટા પ્રોટેક્શન ઓફિસર\n**ઇમેઇલ:** dpo@drivinglicenceform.in\n**સરનામું:** પ્રાઇવસી સેલ, ડ્રાઇવિંગ લાયસન્સ ફોર્મ, ગાંધીનગર, ગુજરાત 382010.',
'DPDP એક્ટ 2023 હેઠળ વિગતવાર નોટિસ જે ડેટા સંગ્રહ, હેતુ, અધિકારો અને ફરિયાદ સંપર્કની માહિતી આપે છે.',
'["application_processing","identity_verification","service_communication","payment_processing","document_verification","security","legal_compliance"]',
'["identity","contact","address","biometric","documents","financial"]',
'published') ON CONFLICT DO NOTHING;
-- 5. SEED DATA PROCESSORS
INSERT INTO data_processors (id, code, name, vendor, service_type, country, storage_location, processor_status, contract_status, security_review_status, deletion_capability, incident_contact_email, incident_contact_phone) VALUES
(1, 'cloud_infra', 'Government Cloud Secure Hosting', 'NIC / MeitY Empaneled Cloud', 'cloud_hosting', 'India', 'India (Mumbai & Pune Tier-4 Data Centers)', 'contracted', 'active', 'approved', 1, 'soc@cloudinfra.gov.in', '+91 11 2436 0199'),
(2, 'object_store', 'Encrypted Private Object Storage', 'SecureVault Cloud Storage India', 'object_storage', 'India', 'India (Hyderabad Encrypted Bucket)', 'contracted', 'active', 'approved', 1, 'security@securevault.in', '+91 40 6600 1234'),
(3, 'payment_gateway', 'Authorised Payment Aggregator', 'Razorpay Payments India Ltd', 'payment_gateway', 'India', 'India (RBI Compliant Data Vault)', 'contracted', 'active', 'approved', 0, 'security@razorpay.com', '+91 80 4666 9999'),
(4, 'sms_gateway', 'TRAI DLT Registered SMS Service', 'CDAC National SMS Gateway', 'sms_provider', 'India', 'India (New Delhi Gov Cloud)', 'contracted', 'active', 'approved', 1, 'dlt-support@cdac.in', '+91 11 2618 1234') ON CONFLICT DO NOTHING;
INSERT INTO processor_contracts (id, processor_id, contract_reference, dpa_signed, effective_from, expires_at, status) VALUES
(1, 1, 'CTR-NIC-2026-001', 1, '2026-01-01', '2027-12-31', 'active'),
(2, 2, 'CTR-SV-2026-042', 1, '2026-01-01', '2027-12-31', 'active'),
(3, 3, 'CTR-RZP-2025-889', 1, '2025-06-01', '2027-05-31', 'active'),
(4, 4, 'CTR-CDAC-2026-112', 1, '2026-01-01', '2028-12-31', 'active') ON CONFLICT DO NOTHING;